apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xr9yi07wv-nodejs
  janus-idp.io/tekton: xr9yi07wv-nodejs
  backstage.io/kubernetes-id: xr9yi07wv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xr9yi07wv-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
